CREATE TABLE usertbl (
    id INT(5) NOT NULL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    userlevel VARCHAR (100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;